"""Books table

Revision ID: 002b0b43f222
Revises: 735e9fe444c5
Create Date: 2024-02-01 16:18:03.358832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002b0b43f222'
down_revision = '735e9fe444c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('available_copies', sa.Integer(), nullable=True),
    sa.Column('total_copies', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('books')
    # ### end Alembic commands ###
