"""Initial Migration

Revision ID: 735e9fe444c5
Revises: 
Create Date: 2024-02-01 14:24:13.673053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735e9fe444c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=16), nullable=False),
    sa.Column('last_name', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=56), nullable=False),
    sa.Column('password_hash', sa.String(length=76), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
